body:
  - type: dropdown
    id: environment
    attributes:
      label: 你的运行环境是?
      options:
        - cs50.dev
        - Windows
        - Linux
        - WSL
        - MacOS
    validations:
      required: true
  - type: textarea
    attributes:
      value: |
        <!-- 请详细描述你的问题，操作步骤。并附上完整的报错信息截图，或其他有效信息。-->
    validations:
      required: true
